### ISSUE TITLE
I18N Review

### ISSUE THREAD

**Issue by iherman** [w3c/json-ld-wg#93]
## Intro

This a shortened version of the [i18n questionnaire](https://www.w3.org/International/techniques/developing-specs?collapse). Following the [Short i18n review checklist](https://w3c.github.io/i18n-drafts/techniques/shortchecklist), the original list has been pruned, retaining only the sections that are relevant to the JSON-LD Specs. Comments have been added, when necessary/possible in _italics_.

The glaring issue is of course the text direction question, but that is now subject of a separate discussion. But that _may_ end up as a topic for a separate Working Group (see a [draft charter](https://w3c.github.io/rdf-dir-literal/draft-charter.html)), and the JSON-LD Working Group should follow what is happening there.

---

### Language basics
1. [x] <a class="self" href="#lang_basics_1">​</a>It should be possible to associate a language with any piece of natural language text that will be read by a user. <a class="local" href="https://w3c.github.io/bp-i18n-specdev/#sec_lang_decl">more</a> 
2. [x] <a class="self" href="#lang_basics_inline">​</a>Where possible, there should  be a way to label natural language changes in inline text. <a class="local" href="https://w3c.github.io/bp-i18n-specdev/#sec_lang_decl">more</a>
    - _Not applicable_
3. [x] <a class="self" href="#lang_basics_meta">​</a>Consider whether it is useful to express the <a href="https://w3c.github.io/bp-i18n-specdev/#sec_lang_meta">intended linguistic audience</a> of a resource, in addition to specifying the language used for <a href="https://w3c.github.io/bp-i18n-specdev/#sec_text_processing_lang">text processing</a>. <a class="local" href="https://w3c.github.io/bp-i18n-specdev/#sec_lang_decl">more</a>
    - _Not applicable_
4. [x] <a class="self" href="#tp_lang_values">​</a>A language declaration that indicates the <a href="https://w3c.github.io/bp-i18n-specdev/#sec_text_processing_lang">text processing language</a> for a range of text must associate  a single language  value with a specific range of text. <a class="local" href="https://w3c.github.io/bp-i18n-specdev/#sec_text_processing_lang">more</a>
5. [x] <a class="self" href="#lang_attribute_xml">​</a>Use the HTML <code class="kw" translate="no">lang</code> and XML <code class="kw" translate="no">xml:lang</code> language attributes where appropriate to identify the <a href="https://w3c.github.io/bp-i18n-specdev/#sec_text_processing_lang">text processing language</a>, rather than creating a new attribute or mechanism. <a class="local" href="https://w3c.github.io/bp-i18n-specdev/#lang_attribute_xml">more</a>
    - _Not really applicable, though the user may use `rdf:HTML` datatype with these tags_
6. [x] <a class="self" href="#metadata_lang_values">​</a>It should be possible to associate a  metadata-type language declaration (which indicates the intended use of the resource rather than the language of a specific range of text)  with multiple language  values. <a class="local" href="https://w3c.github.io/bp-i18n-specdev/#sec_lang_meta">more</a>
    - _This may translate into the fact of expressing language changes within one literal; this can be done using `rdf:HTML`_
7. [x] <a class="self" href="#metadata_not_lang">​</a>Attributes that express the language of external resources should not use the HTML <code class="kw" translate="no">lang</code> and XML <code class="kw" translate="no">xml:lang</code> language attributes, but should use a different attribute when they represent metadata (which indicates the intended use of the resource rather than the language of a specific range of text). <a class="local" href="https://w3c.github.io/bp-i18n-specdev/#sec_lang_meta">more</a>
    - _Not applicable: JSON-LD does not add _any_ metadata to external references (i.e., URL-s)._

### Defining language values
1. [x] <a class="self" href="#lang_use_bcp47">​</a>Values for language declarations must use BCP 47. <a class="local" href="https://w3c.github.io/bp-i18n-specdev/#sec_lang_values">more</a>
1. [x] <a class="self" href="#lang_bcp_not_rfc">​</a>Refer to BCP 47, not to RFC 5646. <a class="local" href="https://w3c.github.io/bp-i18n-specdev/#sec_lang_values">more</a>
1. [x] <a class="self" href="#lang_values_valid">​</a>Be specific about what level of conformance you expect for language tags. The word "valid" has special meaning in BCP 47. Generally "well-formed" is a better choice.
1. [x] <a class="self" href="#lang_matching_bcp">​</a>Reference BCP47 for language tag matching.

### Declaring  language at the resource level
1. [x] <a class="self" href="#lang_whole_res">​</a>The specification should indicate how to define the default text-processing language for the resource as a whole. <a class="local" href="https://w3c.github.io/bp-i18n-specdev/#lang_whole_res">more</a>
1. [x] <a class="self" href="#lang_inherit">​</a>Content within the resource should inherit the language of the text-processing declared at the resource level, unless it is specifically overridden.
1. [x] <a class="self" href="#lang_tp_meta">​</a>Consider whether it is necessary to have separate declarations to indicate the text-processing language versus metadata about the expected use of the resource. <a class="local" href="https://w3c.github.io/bp-i18n-specdev/#lang_tp_meta">more</a>
1. [x] <a class="self" href="#lang_mixing">​</a>If there is only one language declaration for a resource, and it has more than one language tag as a value, it must be possible to identify the default text-processing language for the resource. <a class="local" href="https://w3c.github.io/bp-i18n-specdev/#lang_tp_meta">more</a>

### Establishing the language of a content block
1. [x] <a class="self" href="#lang_block_inherit">​</a>By default, blocks of content should inherit any text-processing language set for the resource as a whole.   <a class="local" href="https://w3c.github.io/bp-i18n-specdev/#lang_block_inherit">more</a>
1. [x] <a class="self" href="#lang_block_change">​</a>It should be possible to indicate a change in language for blocks of content where the language changes. <a class="local" href="https://w3c.github.io/bp-i18n-specdev/#lang_block_change">more</a>

### Establishing the language of inline runs
1. [x] <a class="self" href="#lang_inline_spans">​</a>It should be possible to indicate language for spans of inline text where the language changes. <a class="local" href="https://w3c.github.io/bp-i18n-specdev/#lang_inline_spans">more</a>
    - _Not applicable_ 

## Text direction

_JSON-LD does not currently handle text directions due to the defficiencies of RDF. See [separate discussion](https://w3c.github.io/rdf-dir-literal/) that MAY lead to a possible solution, albeit possibly in a later version of JSON-LD only. The answers below are answered WITH THE ASSUMPTION that a separate `@direction` is introduced (now or later) alongside `@language`._

### Basic requirements
1. [x] <a class="self" href="#dir_paragraphs">​</a>It must be possible to indicate base direction for each individual paragraph-level item of natural language text that will be read by someone. <a class="local" href="https://w3c.github.io/bp-i18n-specdev/#dir_paragraphs">more</a>
1. [x] <a class="self" href="#dir_inline">​</a>It must be possible to indicate base direction changes for embedded runs of inline bidirectional text for all natural language text that will be read by someone. <a class="local" href="https://w3c.github.io/bp-i18n-specdev/#dir_inline">more</a>
   - _this is doable via the usage of `rdf:HTML`_
1. [x] <a class="self" href="#dir_inline">​</a>Annotating right-to-left text must require the minimum amount of effort for people who work natively with right-to-left scripts. <a class="local" href="https://w3c.github.io/bp-i18n-specdev/#dir_reasonable">more</a>

### Background information
1. [x] <a class="self" href="#bidi_lang">​</a>Do not assume that direction can be determined from language information. <a class="local" href="https://w3c.github.io/bp-i18n-specdev/#bidi_lang">more</a>

### Base direction values
1. [x] <a class="self" href="#bidi_values">​</a>Values for the default base direction should include left-to-right, right-to-left, and auto. <a class="local" href="https://w3c.github.io/bp-i18n-specdev/#bidi_values">more</a>
    - _It is unclear whether `auto` is meaningful in JSON-LD. But can be easily done if necessary_ 

### Handling direction in markup
1. [x] <a class="self" href="#bidi_whole_res">​</a>The spec should  indicate how to define a default base direction for the resource as a whole, ie. set the overall base direction. <a class="local" href="https://w3c.github.io/bp-i18n-specdev/#bidi_whole_res">more</a>
1. [X] <a class="self" href="#bidi_res_default">​</a>The default base direction, in the absence of other information, should be LTR. <a class="local" href="https://w3c.github.io/bp-i18n-specdev/#bidi_res_default">more</a>
    - _can be defined alongside `@direction`, just like `@language`._
1. [x] <a class="self" href="#bidi_block_change">​</a>The content author must be able to indicate parts of the text where the base direction changes. At the block level, this should be achieved using attributes or metadata, and should not rely on Unicode control characters.
    - _This can only be done using `rdf:HTML`. JSON-LD does not provide information inside a literal_
1. [x] <a class="self" href="#bidi_block_auto">​</a>It must be possible to also set the direction for content fragments to <code class="kw" translate="no">auto</code>. This means that the base direction will be determined by examining the content itself.
    - _Not applicable_
1. [x] <a class="self" href="#bidi_block_para">​</a>If the overall base direction is set to <code class="kw" translate="no">auto</code> for plain text, the direction of content paragraphs should be determined on a paragraph by paragraph basis.
1. [x] <a class="self" href="#bidi_block_befaft">​</a>To indicate the sides of a block of text where relative to the start and end of its contained lines, you should use 'before' and 'after' (maybe block-start/block-end – the terminology is changing), rather than 'top' and 'bottom'. 
    - _Not applicable_
1. [x] <a class="self" href="#bidi_inline_start_end">​</a>To indicate the start/end of a line  you should use 'start' and 'end' rather than 'left' and 'right'. 
    - _Not applicable_
1. [x] <a class="self" href="#bidi_dedicated_attr">​</a>Provide dedicated attributes for control of base direction and bidirectional overrides; do not rely on the user applying style properties to arbitrary markup to achieve bidi control.
    - _Not applicable_

### Handling base direction for strings
1. [x] <a class="self" href="#bidi_strings_metadata">​</a>Provide metadata constructs that can be used to indicate the base direction of any natural language string. <a href="https://w3c.github.io/string-meta/#best-practices-recommendations-and-gaps">more</a>
1. [x] <a class="self" href="#bidi_strings_metadata">​</a>Specify that consumers of strings should use  heuristics, preferably based on the Unicode Standard first-strong algorithm, to detect the base direction of a string except where metadata is provided. <a href="https://w3c.github.io/string-meta/#best-practices-recommendations-and-gaps">more</a>
    - _Not applicable_
1. [x] <a class="self" href="#bidi_strings_default">​</a>Where possible, define a field to  indicate the default direction for all strings in a given resource or document. <a href="https://w3c.github.io/string-meta/#best-practices-recommendations-and-gaps">more</a>
1. [x] <a class="self" href="#bidi_strings_metadata_and_default">​</a>Do NOT assume that a creating a document-level default without the ability to change direction for any string is sufficient. <a href="https://w3c.github.io/string-meta/#best-practices-recommendations-and-gaps">more</a>
1. [x] <a class="self" href="#bidi_strings_script_tag">​</a>If metadata is not available due to legacy implementations and cannot otherwise be provided, specifications <em class="rfc2119" title="MAY">MAY</em> allow a base direction to be interpolated from available language metadata. <a href="https://w3c.github.io/string-meta/#best-practices-recommendations-and-gaps">more</a>
    - _This is the current assumption, actually_
1. [x] <a class="self" href="#bidi_strings_paired_controls">​</a>Specifications <em class="rfc2119" title="MUST NOT">MUST NOT</em> require the production or use of paired bidi controls. <a href="https://w3c.github.io/string-meta/#best-practices-recommendations-and-gaps">more</a>

### Setting base direction for inline or substring text

_For the whole section: JSON-LD does not, and should not, provide means to specify the "internals" of Literal and the way receiving applications handle Literals. (Using `rdf:HTML`, if necessary, can be used for this, but that is not a matter of JSON-LD. This makes all the points in this section not applicable._

1. [x] <a class="self" href="#bidi_inline_change">​</a>It must be possible to indicate spans of inline text where the base direction changes. If markup is available, this is the preferred method. Otherwise your specification must require that Unicode control characters are recognized by the receiving application, and correctly implemented.
    - _JSON-LD cannot make asuumption or requirements on the receiving application; in this case it "just" transfers data._
1. [x] <a class="self" href="#bidi_inline_auto">​</a>It must be possible to also set the direction for a span to auto. This means that the base direction will be determined by examining the content itself. A typical approach here would be to set the direction based on the first strong directional character outside of any markup. <a class="local" href="https://w3c.github.io/bp-i18n-specdev/#bidi_inline_auto">more</a>
1. [x] <a class="self" href="#bidi_inline_rli">​</a>If users use Unicode bidirectional control characters, the isolating RLI/LRI/FSI with PDI characters must be supported by the application and recommended (rather than RLE/LRE with PDF) by the spec.
1. [x] <a class="self" href="#bidi_inline_rlm">​</a>Use of RLM/LRM should be appropriate, and expectations of what those controls can and cannot do should be clear in the spec. <a class="local" href="https://w3c.github.io/bp-i18n-specdev/#bidi_inline_rlm">more</a>
1. [x] <a class="self" href="#bidi_inline_dedicated_attr">​</a>For markup, provide dedicated attributes for control of base direction and bidirectional overrides; do not rely on the user applying style properties to arbitrary markup to achieve bidi control.
1. [x] <a class="self" href="#bidi_inline_all_elems">​</a>For markup, allow bidi attributes on all inline elements in markup that contain text.
1. [x] <a class="self" href="#bidi_inline_embed">​</a>For markup, provide attributes that allow the user to (a) create an embedded base direction or (b) override the bidirectional algorithm altogether; the attribute should allow the user to set the direction to LTR or RTL or the aforementioned Auto in either of these two scenarios.

**Comment by asmusf** [comment]
Would it be fair to say that JSON-LD "supports" the use of RLI/LRI/FSI with PDI and RLM/LRM that are in literals? (Even if that support is in form of pass-through?). Should the spec recommend that RLE/LRE with PDF be avoided in literals (as best practice)?

**Comment by iherman** [comment]
@asmusf, "supports" may indeed be the right term.  JSON-LD does not put any constraints, nor does it define any internal structure, on string literals apart from the fact that a string is defined as "a sequence of zero or more Unicode (UTF-8)" (see the [terminology section](https://www.w3.org/TR/json-ld11/#terminology)).  Meaning that, indeed, all Unicode control characters are usable.

I am not sure, however, that it is appropriate for the JSON-LD specification to talk about best practices for such a complex subject. Instead, the document, in its [I18N section](https://www.w3.org/TR/json-ld11/#internationalization), refers to the [string-meta](https://www.w3.org/TR/string-meta/) note which, I think, is the right place to provide such information.

Cc: @gkellogg @pchampin

**Comment by iherman** [comment]
@r12a @aphillips : can we consider the I18N horizontal review as officially done for this specification?

**Comment by azaroth42** [comment]
Propose to call this done after TPAC
